### ISSUE TITLE
Low output image resolution

### ISSUE THREAD

**Issue by wizyoung** [JoshData/pdf-diff#20]
Hi, I find the output diff image is in low resolution, and the words are not that clear on my screen. Is there a way to make the output image in high resolution (or just lossless) ?

**Comment by danisowa** [comment]
Hi, i had the same question.
i just changed the line
def pdftopng(pdffile, pagenumber, width=900):
to
def pdftopng(pdffile, pagenumber, width=1900):

maybe in a future rlease the resolution could be a switch for the tool
pdf-diff -img_res=1900 .....

**Comment by wizyoung** [comment]
@danisowa Thanks, this method works! I think you can pull a request.
