### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Liam3851** [JoshData/pdf-diff#36]
Right now pdf-diff depends on /dev/stdout being valid and so only works on OSX and Linux. I have a workaround written that detects the Windows platform and uses a tempfile for pdftotext output instead of /dev/stdout which we use on Windows machines here with some success.

Is this the right place to submit a PR? I see that pdf-diff3 on pypi has a slightly higher version than master, links to this github repo and is mostly the same code, but lists a different maintainer.

**Comment by JoshData** [comment]
Hey.

Before making a PR to use a temp file, does passing `-` (a dash) in place of `/dev/stdout` to `pdftotext` solve it? Unix commands usually interpret a dash as stdin/stdout, and it's possible that will work cross-platform. (Windows has stdout, it's just not ever called `/dev/stdout`.)

If that doesn't solve it, I'd be glad to accept a simple PR that makes the library cross-platform.

**Comment by JoshData** [comment]
Oh and `pdf-diff3` is not me, and it's suspicious. I would not touch that. I will look into it.

**Comment by Liam3851** [comment]
Thanks for the heads-up on pdf-diff3. We're actually having trouble installing pdf-diff using pip which was how we got to pdf-diff3. Maybe the was a broken PyPI recipe and someone re-uploaded the package rather than doing a PR here?

```batch
(py36) C:\projects\python>pip install pdf-diff
Collecting pdf-diff
  ERROR: Could not find a version that satisfies the requirement pdf-diff (from versions: none)
ERROR: No matching distribution found for pdf-diff
```

**Comment by JoshData** [comment]
Indeed, I think I botched the package on pypi when I set it up a few years ago.

If you're planning on making a PR for Windows compatibility, I'd like to hold off until that's in before making a release.

**Comment by Liam3851** [comment]
Sorry, took me a bit to get back to this, but per your earlier suggestion just changing "/dev/stdout" to "-" at command_line.py:64 fixes the issue on Windows and works on Ubuntu as well. Would you like me to submit a PR for this change?

**Comment by JoshData** [comment]
Yes please!

On June 11, 2019 2:30:04 PM EDT, David Krych <notifications@github.com> wrote:
>Sorry, took me a bit to get back to this, but per your earlier
>suggestion just changing "/dev/stdout" to "-" at command_line.py:64
>fixes the issue on Windows and works on Ubuntu as well. Would you like
>me to submit a PR for this change? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/JoshData/pdf-diff/issues/36#issuecomment-500967346

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JoshData** [comment]
I think I've now fixed the pypi distribution so pip should work.

**Comment by Liam3851** [comment]
Thanks Josh, I just installed 0.9.1 using pip on both Python 2.7 and Python 3.6 on Windows and it works out of the box.

**Comment by JoshData** [comment]
Excellent, thanks for letting me know.
