### ISSUE TITLE
Syntax Warning: Invalid Font Weight

### ISSUE THREAD

**Issue by todrobbins** [JoshData/pdf-diff#4]
Not sure if this warning is a pdf.js error (since I went with https://github.com/JoshData/pdf-diff#node-version being on OSX) or a pdf-diff error:

```
➜  pdf-diff git:(master) ✗ python3 pdf-diff.py --changes < changes.json > test.png
Syntax Warning: Invalid Font Weight
Syntax Warning: Invalid Font Weight
Syntax Warning: Invalid Font Weight
Syntax Warning: Invalid Font Weight
Syntax Warning: Invalid Font Weight
Syntax Warning: Invalid Font Weight
```

The output turned out alright, so I'm not sure what's going on. Thanks!

**Comment by uldics** [comment]
That means you have a PDF object definition with non standard value, for example "/FontWeight 350/". If you open the PDF file in a text editor, you can find it. From PDF specification on Adobe site:
`The Weight (thickness) component of the fully qualified font name or font speciﬁer. The possible values shall be 100, 200, 300, 400, 500, 600, 700, 800, or 900, where each number indicates a weight that is at least as dark as its predecessor. A value of 400 shall indicate a normal weight; 700 shall indicate bold.`
